reset;

model C:\Users\dawre\Desktop\TESI_RO\models\chemo1.mod;

table cancerTable IN "ODBC" "Data\cancerType.xls" "cancer_types":
    PATH <- [ID], CodK, MainCatK, visit_time, infusion_time, DescrizioneK;

table clinicianTable IN "ODBC" "Data\oncologists.xls" "clinician_work":
    CLIN <- [NOME], KAPPA1, KAPPA2, LUN, MAR, MER, GIO, VEN;

table accessiTable IN "ODBC" "Data\accessi.xls" "Accessi":
    ACES <- [ID_accesso], ID_paziente, KAPPA_1, KAPPA_2, KAPPA_3, KAPPA_4, Settimana, Mese, 
            farmaco1, reparto, data_prevista, data_allestimento, farmaco2;

read table cancerTable;
read table clinicianTable;
read table accessiTable;

display PATH, CodK, MainCatK, visit_time , infusion_time, DescrizioneK;
display CLIN, KAPPA1, KAPPA2, LUN, MAR, MER, GIO, VEN;
display ACES;